'use client';
import {useEffect,useMemo,useState} from 'react';
import {ArrowRight,Check,ChevronDown,Heart,Minus,Plus,Search,ShieldCheck,ShoppingBag,Sparkles,Star,X} from 'lucide-react';

type Product={id:string;name:string;category:string;price:number;compareAt?:number;image:string;description:string;rating:number;reviews:number;stock:number;badge?:string;featured?:boolean};
type CartItem=Product&{quantity:number};
type Pay={bkashNumber:string;bKashAccountType:string;nagadNumber:string;nagadAccountType:string;note:string};
const seed:Product[]=[
{id:'aero',name:'Aero Knit Runner',category:'Footwear',price:4890,compareAt:5990,image:'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85',description:'Breathable everyday sneakers with a lightweight foam sole.',rating:4.8,reviews:184,stock:27,badge:'Best Seller',featured:true},
{id:'tote',name:'Studio Carry Tote',category:'Bags',price:3190,compareAt:3990,image:'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=85',description:'Minimal structured tote for daily essentials.',rating:4.7,reviews:96,stock:41,badge:'New',featured:true},
{id:'hoodie',name:'Cloudline Hoodie',category:'Apparel',price:2890,compareAt:3490,image:'https://images.unsplash.com/photo-1556821840-3a63f95609a7?auto=format&fit=crop&w=900&q=85',description:'Soft brushed cotton hoodie for cool evenings.',rating:4.9,reviews:211,stock:34,badge:'Top Rated',featured:true},
{id:'lamp',name:'Solis Desk Lamp',category:'Home',price:2590,compareAt:3190,image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=85',description:'Warm ambient desk lighting with a sculptural profile.',rating:4.6,reviews:72,stock:18},
{id:'phones',name:'Echo Wireless Headphones',category:'Tech',price:6790,compareAt:7990,image:'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=900&q=85',description:'Comfort-first wireless headphones with deep bass.',rating:4.8,reviews:327,stock:13,badge:'Limited'},
{id:'ceramic',name:'Terra Ceramic Set',category:'Home',price:1990,compareAt:2490,image:'https://images.unsplash.com/photo-1610701596007-11502861dcfa?auto=format&fit=crop&w=900&q=85',description:'Hand-finished neutral-toned ceramic pair.',rating:4.5,reviews:54,stock:22,badge:'Fresh Drop'}];
const categories=['All','Footwear','Bags','Apparel','Home','Tech'];
const payDefault:Pay={bkashNumber:'01768780058',bKashAccountType:'Personal',nagadNumber:'',nagadAccountType:'Personal',note:'Pay only through the official bKash or Nagad app. LUMA will never ask for your PIN, OTP, or security code.'};
const money=(n:number)=>new Intl.NumberFormat('en-BD',{style:'currency',currency:'BDT',maximumFractionDigits:0}).format(n);
const read=<T,>(k:string,f:T)=>{try{const v=localStorage.getItem(k);return v?JSON.parse(v) as T:f}catch{return f}};
export default function Home(){
 const[products,setProducts]=useState<Product[]>(seed),[cart,setCart]=useState<CartItem[]>([]),[fav,setFav]=useState<string[]>([]),[settings,setSettings]=useState(payDefault),[cat,setCat]=useState('All'),[q,setQ]=useState(''),[sort,setSort]=useState('featured'),[drawer,setDrawer]=useState(false),[checkout,setCheckout]=useState(false),[notice,setNotice]=useState(''),[copied,setCopied]=useState(false),[user,setUser]=useState<{name:string;email:string}|null>(null);
 const[form,setForm]=useState({name:'',phone:'',line1:'',city:'Dhaka',postalCode:'',payment:'Cash on Delivery',senderNumber:'',transactionId:''});
 useEffect(()=>{setProducts(read('luma-products',seed));setCart(read('luma-cart',[]));setFav(read('luma-favorites',[]));setSettings(read('luma-payment-settings',payDefault));setUser(read('luma-user',null));},[]);
 useEffect(()=>localStorage.setItem('luma-products',JSON.stringify(products)),[products]);
 useEffect(()=>localStorage.setItem('luma-cart',JSON.stringify(cart)),[cart]);
 useEffect(()=>localStorage.setItem('luma-favorites',JSON.stringify(fav)),[fav]);
 const filtered=useMemo(()=>[...products.filter(p=>(cat==='All'||p.category===cat)&&((p.name+' '+p.category+' '+p.description).toLowerCase().includes(q.toLowerCase())))].sort((a,b)=>sort==='price-low'?a.price-b.price:sort==='price-high'?b.price-a.price:sort==='rating'?b.rating-a.rating:Number(!!b.featured)-Number(!!a.featured)),[products,cat,q,sort]);
 const count=cart.reduce((s,x)=>s+x.quantity,0),subtotal=cart.reduce((s,x)=>s+x.price*x.quantity,0),shipping=subtotal>=5000||subtotal===0?0:120,total=subtotal+shipping;
 const add=(p:Product)=>{if(p.stock<1)return setNotice('This product is out of stock.');setCart(c=>{const x=c.find(i=>i.id===p.id);return x?c.map(i=>i.id===p.id?{...i,quantity:Math.min(i.stock,i.quantity+1)}:i):[...c,{...p,quantity:1}]});setNotice(p.name+' added to your bag.')};
 const change=(id:string,d:number)=>setCart(c=>c.map(i=>i.id===id?{...i,quantity:Math.max(0,Math.min(i.stock,i.quantity+d))}:i).filter(i=>i.quantity>0));
 const place=()=>{if(!form.name||!form.phone||!form.line1||!form.city)return setNotice('Please complete your shipping details.');if(form.payment!=='Cash on Delivery'&&(!form.senderNumber||!form.transactionId))return setNotice('Enter the sender number and Transaction ID after payment.');if(form.payment!=='Cash on Delivery'&&!settings.bkashNumber)return setNotice('Payment method is not configured.');const orders=read<any[]>('luma-orders',[]);const o={id:crypto.randomUUID(),createdAt:new Date().toISOString(),total,status:'pending',paymentMethod:form.payment,paymentStatus:form.payment==='Cash on Delivery'?'unpaid':'pending',manualPayment:form.payment!=='Cash on Delivery'?{method:form.payment,senderNumber:form.senderNumber,transactionId:form.transactionId}:undefined,items:cart.map(i=>({name:i.name,quantity:i.quantity,price:i.price,image:i.image}))};localStorage.setItem('luma-orders',JSON.stringify([o,...orders]));setCart([]);setCheckout(false);setDrawer(false);window.location.href='payment-result?status='+encodeURIComponent(form.payment==='Cash on Delivery'?'success':'pending')+'&order='+encodeURIComponent(o.id)+'&amount='+o.total;};
 return <main className="store-shell">
  <header className="topbar"><a className="brand" href="/"><span className="brand-mark">L</span><span><strong>LUMA</strong><small>commerce studio</small></span></a><nav><a href="#shop">Shop</a><a href="#categories">Categories</a><a href="#about">About</a></nav><div className="header-actions"><a className="text-link" href="/account">Account{user?.name?' · '+user.name.split(' ')[0]:''}</a><button className="icon-btn" onClick={()=>setDrawer(true)} aria-label="Open bag"><ShoppingBag size={19}/>{count>0&&<span className="cart-bubble">{count}</span>}</button></div></header>
  <section className="hero"><div className="hero-copy"><div className="eyebrow"><Sparkles size={14}/> NEW SEASON / 2026</div><h1>Curated goods for everyday life.</h1><p>Thoughtful essentials, elevated design, and dependable quality in one calm shopping space.</p><div className="hero-actions"><a className="primary-btn" href="#shop">Explore collection <ArrowRight size={16}/></a><a className="secondary-btn" href="/signup">Create account</a></div><div className="trust-row"><span><Check size={14}/> Clear checkout</span><span><Check size={14}/> Local delivery</span><span><Check size={14}/> Account history</span></div></div><div className="hero-art"><div className="hero-orb orb-one"/><div className="hero-orb orb-two"/><div className="hero-card"><span>EDITOR'S PICK</span><img src={seed[0].image} alt="Aero Knit Runner"/><div><strong>Aero Knit Runner</strong><small>Minimal profile / everyday pace</small></div></div></div></section>
  <section id="categories" className="category-strip">{categories.map(x=><button key={x} className={cat===x?'category-chip active':'category-chip'} onClick={()=>setCat(x)}>{x}</button>)}</section>
  <section id="shop" className="shop-section"><div className="section-head"><div><span className="eyebrow">THE COLLECTION</span><h2>Shop the edit</h2></div><div className="toolbar"><div className="search-box"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products..."/></div><label className="sort-box"><ChevronDown size={14}/><select value={sort} onChange={e=>setSort(e.target.value)}><option value="featured">Featured</option><option value="rating">Top rated</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select></label></div></div>
  <div className="product-grid">{filtered.map(p=><article className="product-card" key={p.id}><div className="product-media"><img src={p.image} alt={p.name}/>{p.badge&&<span className="badge">{p.badge}</span>}<button className={fav.includes(p.id)?'heart-btn liked':'heart-btn'} onClick={()=>setFav(v=>v.includes(p.id)?v.filter(x=>x!==p.id):[...v,p.id])}><Heart size={16} fill={fav.includes(p.id)?'currentColor':'none'}/></button>{p.stock<6&&<span className="stock-note">Only {p.stock} left</span>}</div><div className="product-info"><div className="product-topline"><span>{p.category}</span><span className="rating"><Star size={12} fill="currentColor"/> {p.rating}</span></div><h3>{p.name}</h3><p>{p.description}</p><div className="product-bottom"><div><strong>{money(p.price)}</strong>{p.compareAt&&<del>{money(p.compareAt)}</del>}</div><button className="add-btn" onClick={()=>add(p)}><Plus size={15}/> Add</button></div></div></article>)}</div></section>
  <section id="about" className="feature-band"><div><span className="eyebrow">LUMA PROMISE</span><h2>Simple shopping.<br/>More thoughtful choices.</h2></div><div className="promise-grid"><div><strong>01</strong><h3>Curated</h3><p>Fewer, better products selected around daily life.</p></div><div><strong>02</strong><h3>Transparent</h3><p>Clear pricing, stock, delivery details, and payment proof.</p></div><div><strong>03</strong><h3>Account-first</h3><p>Orders stay connected to your local LUMA account.</p></div></div></section>
  <footer className="footer"><div><strong>LUMA</strong><span>commerce studio</span></div><div className="footer-links"><a href="/account">My account</a><a href="/login">Sign in</a><a href="/admin-login">Admin login</a></div><span>© 2026 LUMA Commerce</span></footer>
  {notice&&<div className="toast"><span>{notice}</span><button onClick={()=>setNotice('')}><X size={15}/></button></div>}
  {drawer&&<div className="drawer-backdrop" onClick={()=>setDrawer(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><div><span className="eyebrow">YOUR BAG</span><h2>{count} item{count===1?'':'s'}</h2></div><button className="icon-btn" onClick={()=>setDrawer(false)}><X size={18}/></button></div><div className="drawer-list">{cart.length?cart.map(i=><div className="cart-row" key={i.id}><img src={i.image} alt=""/><div className="cart-main"><strong>{i.name}</strong><span>{money(i.price)}</span><div className="qty"><button onClick={()=>change(i.id,-1)}><Minus size={13}/></button><b>{i.quantity}</b><button onClick={()=>change(i.id,1)}><Plus size={13}/></button></div></div></div>):<div className="empty-state small"><h3>Your bag is empty</h3><p>Add something from the collection.</p></div>}</div><div className="drawer-total"><span>Subtotal</span><strong>{money(subtotal)}</strong></div><button className="primary-btn full" disabled={!cart.length} onClick={()=>{setDrawer(false);setCheckout(true)}}>Checkout <ArrowRight size={15}/></button></aside></div>}
  {checkout&&<div className="modal-backdrop" onClick={()=>setCheckout(false)}><section className="checkout-modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><span className="eyebrow">SECURE CHECKOUT</span><h2>Complete your order</h2></div><button className="icon-btn" onClick={()=>setCheckout(false)}><X size={18}/></button></div><div className="checkout-total"><span>Total</span><strong>{money(total)}</strong></div><div className="field-grid"><label>Full name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Phone<input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></label></div><label>Address<input value={form.line1} onChange={e=>setForm({...form,line1:e.target.value})}/></label><div className="field-grid"><label>City<input value={form.city} onChange={e=>setForm({...form,city:e.target.value})}/></label><label>Postal code<input value={form.postalCode} onChange={e=>setForm({...form,postalCode:e.target.value})}/></label></div><label className="field-label">Payment method</label><div className="payment-options"><button className={form.payment==='Cash on Delivery'?'payment-option active':'payment-option'} onClick={()=>setForm({...form,payment:'Cash on Delivery'})}><span><strong>Cash on Delivery</strong><small>Pay when your order arrives.</small></span></button><button className={form.payment==='bKash'?'payment-option active':'payment-option'} onClick={()=>setForm({...form,payment:'bKash'})}><span><strong>bKash · Manual payment</strong><small>Send the exact amount in the official bKash app.</small></span></button></div>{form.payment==='bKash'&&<div className="manual-payment-panel"><div className="manual-top"><div><span className="eyebrow">SEND TO</span><strong>{settings.bkashNumber||'Not configured'}</strong><small>{settings.bKashAccountType}</small></div><button className="secondary-btn" onClick={()=>{navigator.clipboard?.writeText(settings.bkashNumber);setCopied(true);setTimeout(()=>setCopied(false),1200)}}>{copied?'Copied':'Copy number'}</button></div><div className="payment-amount-card"><span>Exact amount</span><strong>{money(total)}</strong></div><div className="payment-steps"><span>1. Open the official bKash app.</span><span>2. Send exactly {money(total)} to the number above.</span><span>3. Enter your sender number and Transaction ID here.</span></div><div className="field-grid"><label>Sender number<input value={form.senderNumber} onChange={e=>setForm({...form,senderNumber:e.target.value})}/></label><label>Transaction ID<input value={form.transactionId} onChange={e=>setForm({...form,transactionId:e.target.value})}/></label></div><div className="payment-safety"><ShieldCheck size={15}/><span>{settings.note}</span></div></div>}<button className="primary-btn full" onClick={place}>Place order <ArrowRight size={15}/></button></section></div>}
 </main>}
